x-env-settings:
  - &POSTGRES_USER ${POSTGRES_USER:-dev_user}
  - &POSTGRES_PASSWORD ${POSTGRES_PASSWORD:-dev_password}
  - &POSTGRES_DB ${POSTGRES_DB:-dev_db}
  - &REDIS_USER ${REDIS_USER:-}
  - &REDIS_PASSWORD ${REDIS_PASSWORD:-}  

services:
  postgres:
    image: postgres:16.3-alpine3.20
    restart: unless-stopped
    profiles:
      - deployment
    environment:
      POSTGRES_USER: *POSTGRES_USER
      POSTGRES_PASSWORD: *POSTGRES_PASSWORD
      POSTGRES_DB: *POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-dev:
    image: postgres:16.3-alpine3.20
    restart: unless-stopped
    profiles:
      - development
    environment:
      POSTGRES_USER: *POSTGRES_USER
      POSTGRES_PASSWORD: *POSTGRES_PASSWORD
      POSTGRES_DB: *POSTGRES_DB
    ports:
      - '5432:5432'
  redis:
    image: redis:7.2.5-alpine
    restart: unless-stopped
    profiles:
      - deployment
      - development
    environment:
      REDIS_USER: *REDIS_USER
      REDIS_PASSWORD: *REDIS_PASSWORD
    ports:
      - '6379:6379'

  app:
    container_name: instance-manager
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    profiles:
      - deployment
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"

volumes:
  postgres_data: