title: Test Challenge
description: super hard
category: pwn
author: hah4
flag: ZEEmk4vlBQFWFidlqn3+vZr1upyY1F0o1CyDfnkc98XK38nHC1EN+cY7OKmS1GeEyzGjg9TJ/t+T7hf5bejfKXtfgPwSLf2DEANDXZoLvTAa4y3ty6K94JSEEkAx8P3z9hUXd7hGAN2vdpmbegr5kVAMOs3gteHb6OJWGjNBR0s=

images:
    - name: image1
      tag: latest
      ports:
          - 3000
          - 2999
      cap_add:
          - SYS_PTRACE
    - name: image2
      tag: latest
      privileged: true
      ports:
          - 8000
      environment:
          key1: value1
          key2: value2
