title: Test Challenge
description: super hard
category: pwn
author: hah4
enc_flag: G0wozEp9MMvXxC9ymRiDnpLztbyW//Q1+5FyxjJ78K4NH461gD2YwOkhQ3wfykqr3cBSdYadE5+SeZQp5yRFJKHPsVH0jKnH5JFb73LpRu7LBQHykRNv4x6sw6ym/k3uAqlUOnZmJQwkT5acHB2g9+KChVJ6VqyspX8603WWTCo=

images:
    - name: nginx
      tag: latest
      ports:
          - 3000
          - 2999
      cap_add:
          - SYS_PTRACE
    - name: redis
      tag: latest
      privileged: true
      ports:
          - 8000
      environment:
          key1: value1
          key2: value2
